### ISSUE TITLE
unable to install

### ISSUE THREAD

**Issue by gbrault** [apiko-dev/Perfi#33]
16:05:53: (node:8348) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 3087): UnableToResolveError: Unable to resolve module `C:\Users\gbrau\git\Perfi\node_modules\remote-redux-devtools\node_modules\socketcluster-client\lib\sctransport.j\lib\ws-browser.js` from `C:\Users\gbrau\git\Perfi\node_modules\remote-redux-devtools\node_modules\socketcluster-client\lib\sctransport.js`: Directory C:\Users\gbrau\git\Perfi\node_modules\remote-redux-devtools\node_modules\socketcluster-client\lib\sctransport.j\lib\ws-browser.js doesn't exist

**Comment by DaxiALex** [comment]
Fixed in the new app version
