### ISSUE TITLE
Cannot be run on Android

### ISSUE THREAD

**Issue by akosmenyhert** [apiko-dev/Perfi#66]
The famous `Cannot Add a child that doesn't have a YogaNode to a parent with out a measure function` error occurred after clicking on the *Getting Started button*.

`[text: 0]`

**Comment by kanji11** [comment]
Same here

**Comment by bhavinmatariya** [comment]
+1

**Comment by DaxiALex** [comment]
Already fixed, If you suddenly repeat, reopen issue again
