### ISSUE TITLE
Question: does this application save data to a database rather than a mobile disk?

### ISSUE THREAD

**Issue by AlexSun98** [apiko-dev/Perfi#69]
does this application save data to a database rather than a mobile disk? thanks.

**Comment by yurakruhlyk** [comment]
@AlexSun98 Hi, no this app doesn`t use a database, only redux-persist which uses [Async Storage ](https://facebook.github.io/react-native/docs/asyncstorage).

**Comment by DaxiALex** [comment]
@AlexSun98 If you have any questions, please open issue again.
