### ISSUE TITLE
remote debugging via chrome

### ISSUE THREAD

**Issue by AlexSun98** [apiko-dev/Perfi#70]
Hi there, 

I come from web based front end background. Wonder if expo+remote-redux-devtools can delivery the similar debugging experience. 

E.G. I start up react native app and debug it via expo. Can I use chrome to check redux state like the way that I did with react web? my dev environment is win10. 

It could be great if you can provide more details or references in steps.  Much appreciated!

**Comment by alex-rentlyz** [comment]
@AlexSun98 Hi,

Yes, of course, you can use Redux DevTools for debugging Perfi, all already configured. All that you need it's be in the same Internet network as your mobile device, run your app and run Redux DevTools. 

If you want to use it with your project you can see how we add devToolsEnhancer in store.js. The process is very easy and similar like in web.
