### ISSUE TITLE
Babel error

### ISSUE THREAD

**Issue by standerpm** [apiko-dev/Perfi#71]
Building iOS bundle
ERROR
19:15
500 - "{\"type\":\"TransformError\",\"lineNumber\":0,\"errors\":[{\"description\":\"node_modules\\\\react-native-scripts\\\\build\\\\bin\\\\crna-entry.js: Plugin/Preset files are not allowed to export objects, only functions. In D:\\\\Desktop\\\\BA\\\\node_modules\\\\babel-preset-expo\\\\index.js\",\"lineNumber\":0}],\"name\":\"SyntaxError\",\"message\":\"node_modules\\\\react-native-scripts\\\\build\\\\bin\\\\crna-entry.js: Plugin/Preset files are not allowed to export objects, only functions. In D:\\\\Desktop\\\\BA\\\\node_modules\\\\babel-preset-expo\\\\index.js\",\"stack\":\"Error: Plugin/Preset files are not allowed to export objects, only functions. In D:\\\\Desktop\\\\BA\\\\node_modules\\\\babel-preset-expo\\\\index.js\\n    at createDescriptor (D:\\\\Desktop\\\\BA\\\\node_modules\\\\@babel\\\\core\\\\lib\\\\config\\\\config-descriptors.js:178:11)\\n    at items.map (D:\\\\Desktop\\\\BA\\\\node_modules\\\\@babel\\\\core\\\\lib\\\\config\\\\config-descriptors.js:109:50)\\n    at Array.map (<anonymous>)\\n    at createDescriptors (D:\\\\Desktop\\\\BA\\\\node_modules\\\\@babel\\\\core\\\\lib\\\\config\\\\config-descriptors.js:109:29)\\n    at createPresetDescriptors (D:\\\\Desktop\\\\BA\\\\node_modules\\\\@babel\\\\core\\\\lib\\\\config\\\\config-descriptors.js:101:10)\\n    at presets (D:\\\\Desktop\\\\BA\\\\node_modules\\\\@babel\\\\core\\\\lib\\\\config\\\\config-descriptors.js:47:19)\\n    at mergeChainOpts (D:\\\\Desktop\\\\BA\\\\node_modules\\\\@babel\\\\core\\\\lib\\\\config\\\\config-chain.js:320:26)\\n    at D:\\\\Desktop\\\\BA\\\\node_modules\\\\@babel\\\\core\\\\lib\\\\config\\\\config-chain.js:283:7\\n    at mergeExtendsChain (D:\\\\Desktop\\\\BA\\\\node_modules\\\\@babel\\\\core\\\\lib\\\\config\\\\config-chain.js:299:21)\"}"
ERROR
19:15
node_modules\react-native-scripts\build\bin\crna-entry.js: Plugin/Preset files are not allowed to export objects, only functions. In D:\Desktop\BA\node_modules\babel-preset-expo\index.js
ERROR
19:15
Building JavaScript bundle: error

**Comment by terrysahaidak** [comment]
Hi @standerpm, could you please post steps you've followed?

**Comment by gurjmatharu** [comment]
+1 

This project is awesome 👍 

This happens on a clean install.
1. Git Clone
2. `npm start`
3. Navigate to expo url on iOS

**Comment by terrysahaidak** [comment]
Seems like our dependencies are outdated, I will update them and write back
